servers:
  # Servers that are allowed everything
  whitelist:
  - server1
  - server2
  channels:
    mode: whitelist
    # Channels to allow in whitelist mode
    whitelist:
      # List of allowed subchannels, use an empty list [] to allow all
      "someplugin:channel": []
    # Channels to block in blacklist mode
    blacklist:
      # List of blocked subchannels, use an empty list [] to block all
      BungeeCord:
      - Forward
      - ServerIP
      - Connect
      - ConnectOther
      "plugin2:channel": []
players:
  # Player bypass permission: blockpluginmessages.bypass[.<channel>]
  channels:
    mode: whitelist
    # Channels to allow in whitelist mode
    whitelist:
      # List of allowed subchannels, use an empty list [] to allow all
      # World name packets used by VoxelMap, Xaero's Map, JourneyMap and Rei's Minimap
      "worldinfo:world_id": []
      "xaeroworldmap:main": []
    # Channels to block in blacklist mode
    blacklist:
      # List of blocked subchannels, use an empty list [] to block all
      BungeeCord: [] # Technically the bungee blocks this itself already
      "another:channel": []